# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-23 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemID', models.IntegerField(default=0, unique=True)),
                ('itemName', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemToUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MILK.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listID', models.IntegerField(default=0, unique=True)),
                ('listName', models.CharField(max_length=128)),
                ('itemQuantity', models.IntegerField(default=1)),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MILK.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestID', models.IntegerField(default=0, unique=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('itemQuantity', models.IntegerField(default=1)),
                ('DateandTime', models.DateTimeField(auto_now_add=True)),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionItem', to='MILK.Item')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(default=0, unique=True)),
                ('userName', models.CharField(max_length=128)),
                ('Balance', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='UserToList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MILK.ShoppingList')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MILK.User')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='purchaserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaserID', to='MILK.User'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='requestorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestorID', to='MILK.ItemToUser'),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ID', to='MILK.User'),
        ),
        migrations.AddField(
            model_name='itemtouser',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MILK.User'),
        ),
    ]
