# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-10 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MILK', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(to='MILK.UserProfile'),
        ),
        migrations.AlterField(
            model_name='group',
            name='administrator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='the_group_creator', to='MILK.UserProfile'),
        ),
    ]
