# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-26 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MILK', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payeeID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='payeeID', to='MILK.User'),
            preserve_default=False,
        ),
    ]
