# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-10 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('MILK', '0002_auto_20170310_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='the_group_creator', to='MILK.UserProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='administrator',
        ),
        migrations.RemoveField(
            model_name='group',
            name='member',
        ),
        migrations.AlterField(
            model_name='usertogroup',
            name='groupID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AddField(
            model_name='groupdetail',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AddField(
            model_name='groupdetail',
            name='member',
            field=models.ManyToManyField(to='MILK.UserProfile'),
        ),
    ]
