# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-27 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MILK', '0002_transaction_payeeid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to=b'profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MILK.User')),
            ],
        ),
    ]
