# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-02 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MILK', '0003_auto_20170302_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='itemID',
        ),
    ]
