# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-10 16:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MILK', '0003_auto_20170310_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdetail',
            name='member',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
