# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-02 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MILK', '0005_auto_20170302_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
