# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-10 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MILK', '0005_auto_20170310_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdetail',
            name='administrator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='the_group_creator', to='MILK.UserProfile'),
        ),
        migrations.AlterField(
            model_name='groupdetail',
            name='member',
            field=models.ManyToManyField(to='MILK.UserProfile'),
        ),
    ]
