# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-10 17:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MILK', '0006_auto_20170310_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdetail',
            name='administrator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='the_group_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupdetail',
            name='member',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
