# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-10 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MILK', '0007_auto_20170310_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupdetail',
            name='member',
        ),
    ]
