# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-03 15:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MILK', '0008_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='group',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='usertogroup',
            name='groupID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MILK.Group'),
        ),
        migrations.AddField(
            model_name='usertogroup',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
