# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-11 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('MILK', '0009_item_groupbuying'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='user',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='groupName',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
