# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-11 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MILK', '0010_auto_20170311_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtouser',
            name='itemID',
        ),
        migrations.RemoveField(
            model_name='itemtouser',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='groupName',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='itemID',
        ),
        migrations.RemoveField(
            model_name='usertolist',
            name='listID',
        ),
        migrations.RemoveField(
            model_name='usertolist',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='requestorID',
        ),
        migrations.AddField(
            model_name='groupdetail',
            name='shoppinglist',
            field=models.ManyToManyField(to='MILK.Item'),
        ),
        migrations.DeleteModel(
            name='ItemToUser',
        ),
        migrations.DeleteModel(
            name='ShoppingList',
        ),
        migrations.DeleteModel(
            name='UserToList',
        ),
    ]
