# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-11 15:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MILK', '0011_auto_20170311_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='addedby',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
