# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-11 17:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MILK', '0012_item_addedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='addedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
