# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-11 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MILK', '0014_auto_20170311_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupdetail',
            name='shoppinglist',
        ),
        migrations.AddField(
            model_name='groupdetail',
            name='shoppinglist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MILK.Item'),
        ),
    ]
