# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-12 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MILK', '0017_auto_20170312_1637'),
        ('MILK', '0014_auto_20170312_1644'),
    ]

    operations = [
    ]
