# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-12 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MILK', '0017_auto_20170312_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertogroup',
            name='groupID',
        ),
        migrations.RemoveField(
            model_name='usertogroup',
            name='userID',
        ),
        migrations.DeleteModel(
            name='UserToGroup',
        ),
    ]
