# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-12 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MILK', '0018_auto_20170312_1814'),
        ('MILK', '0019_remove_userprofile_group'),
    ]

    operations = [
    ]
