# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-13 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MILK', '0021_auto_20170312_2137'),
        ('MILK', '0019_auto_20170312_1947'),
    ]

    operations = [
    ]
