# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-13 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MILK', '0021_auto_20170312_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='itemQuantity',
        ),
    ]
