# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-13 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MILK', '0022_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='DateandTime',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='itemID',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='itemQuantity',
        ),
    ]
