# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-13 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MILK', '0023_remove_transaction_itemid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='purchaserID',
        ),
    ]
