# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-13 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MILK', '0024_remove_transaction_purchaserid'),
        ('MILK', '0023_auto_20170313_1536'),
    ]

    operations = [
    ]
