# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-13 18:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MILK', '0025_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payeeID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payeeID', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
